# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_for_friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='name',
            field=models.CharField(default='Some_String', max_length=50),
        ),
    ]
