# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_for_friends', '0002_messages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
