# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_for_friends', '0003_auto_20180221_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsmessages',
            name='author',
            field=models.CharField(default='myself', max_length=50),
        ),
        migrations.AlterField(
            model_name='memessages',
            name='author',
            field=models.CharField(default='myself', max_length=50),
        ),
    ]
