# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_for_friends', '0006_auto_20180216_0227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendsMeMessages',
            new_name='FriendsMessages',
        ),
    ]
