# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_for_friends', '0007_auto_20180216_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memessages',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
