# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_for_friends', '0009_auto_20180219_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsmessages',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='memessages',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
